### Handling Imbalnced Data Set

1. Up Sampling
2. Down Sampling

In [1]:
import numpy as np
import pandas as pd

# Set the random seed for reproducibility
np.random.seed(123)

# Create a dataframe with two classes
n_samples = 1000
class_0_ratio = 0.9
n_class_0 = int(n_samples * class_0_ratio)
n_class_1 = n_samples - n_class_0

In [2]:
n_class_0, n_class_1

(900, 100)

In [8]:
# Create My Datafranme with imbalanced dataset

class_0 = pd.DataFrame({
    'feature_1': np.random.normal(loc=0, scale=1, size=n_class_0),
    'feature_2': np.random.normal(loc=0, scale=1, size=n_class_0),
    'target': [0] * n_class_0

})


class_1 = pd.DataFrame({
    'feature_1': np.random.normal(loc=0, scale=1, size=n_class_1),
    'feature_2': np.random.normal(loc=0, scale=1, size=n_class_1),
    'target': [1] * n_class_1

})

In [9]:
df = pd.concat([class_0, class_1]).reset_index(drop=True)

In [10]:
df.head()

   feature_1  feature_2  target
0  -0.941691  -0.460530       0
1   1.038645  -0.910269       0
2  -1.432479  -0.780990       0
3  -1.620503  -0.107118       0
4  -0.279527  -0.657885       0

In [11]:
df.tail()

     feature_1  feature_2  target
995   0.080243  -0.799129       1
996  -0.542371   0.371559       1
997   1.456532  -0.456539       1
998   1.046854  -0.139554       1
999  -0.409166  -0.692508       1

In [12]:
df['target'].value_counts()

target
0    900
1    100
Name: count, dtype: int64

In [13]:
# upsampling
df_minority = df[df['target'] == 1]
df_majority = df[df['target'] == 0]

In [14]:
from sklearn.utils import resample

df_minority_upsampled = resample(
    df_minority,
    replace=True,
    n_samples=len(df_majority),
    random_state=42
)

In [15]:
df_minority_upsampled.shape

(900, 3)

In [ ]:
## Downsampling
df_minority = df[df['target'] == 1]
df_majority = df[df['target'] == 0]

In [17]:
df_majority_downsampled = resample(
    df_majority,
    replace=False,
    n_samples=len(df_minority),
    random_state=42
)

In [18]:
df_majority_downsampled.shape

(100, 3)